### ISSUE TITLE
Support for the creation of NIST key pairs in operation `CreateKeyPair`

### ISSUE THREAD

**Issue by bgrieder** [Cosmian/kms#104]
After #101, it will be. possible to import NIST key pairs (P192, P256, P384,... and various RSA), but it is not yet possible to create these.

Adding this functionality will greatly improve the PKI and the ability to create various types of certificates.
Should be done using OpenSSL.

**Comment by Manuthor** [comment]
done in https://github.com/Cosmian/kms/pull/132
