### ISSUE TITLE
Removal of openssl in the CLI

### ISSUE THREAD

**Issue by bgrieder** [Cosmian/kms#105]
This will make the CLI pure Rust and facilitate compiling to various targets.

After #101 , only the `verify.rs` need to be ported to OpenSSL.

**Comment by Manuthor** [comment]
The crate openssl is partially removed from the CLI:

- [x] the "direct" dependency of openssl has been removed from crate/cli/Cargo.toml
- [ ] but `reqwest` is still using the `native-tls` feature required by the KMS Rest Client for handling the SSL PKCS12 client certificate (function `Identity::from_pkcs12_der`)

**Comment by bgrieder** [comment]
josekit prevents the removal of openssl. 
Trying to vendor it so that it can build on Windowa
