### ISSUE TITLE
FIPS version of the Server

### ISSUE THREAD

**Issue by bgrieder** [Cosmian/kms#106]
Create a special `FIPS` version of the server that will only enable FIPS-140 certified crypto modules.

The choice is to use OpenSSL (only) server side in one of its FIPS-140 approved modes.

**Comment by bgrieder** [comment]
@JosePisco Please add details to this issue on the OpenSSL version and possibly the retained algorithms.

**Comment by bgrieder** [comment]
Issue #105 could be tackled as part of this one unless any other urgent need.

**Comment by JosePisco** [comment]
I think this issue can only be resolved once we passed all CoverCrypt arguments as optional in order to build a CC-free binary of the KMS.
Same holds for Hybrid Encryption, I think issue #112 needs to be resolved first.
