### ISSUE TITLE
OpenSSL ECIES for X and Ed curves

### ISSUE THREAD

**Issue by JosePisco** [Cosmian/kms#144]
Hybrid encryption supports ECIES Salsa Sealbox for curves X25519 and Ed25519. In a concern for a growing list of supported algorithm, it would be of interest to have an OpenSSL implementation for curves X25519, X448, Ed25519 and Ed448. They would still be disabled in FIPS mode.

This would allow to completely remove cloudproof dependencies from KMS even in non-fips mode.

**Comment by JosePisco** [comment]
Since OpenSSL does not provide tools to work with points and multiplication on X/Ed25519 or X/Ed448, I don't think the classical salsa sealbox can be done for those curves.

**Comment by Manuthor** [comment]
closing this issue since OpenSSL did not plan to implement points and multiplication on X/Ed25519 or X/Ed448
