### ISSUE TITLE
Zeroize BigUInt keys

### ISSUE THREAD

**Issue by tbrezot** [Cosmian/kms#159]
If I am right, you are using BigUint for storage only. Therefore it should be possible to implement the correct operation on dropping structure that own them (big integers are essentially pointers so they do not leak there content in the memory when they are passed around).

_Originally posted by @tbrezot in https://github.com/Cosmian/kms/pull/149#discussion_r1459156583_

**Comment by JosePisco** [comment]
`DecryptionResponse` struct contains decrypted plaintext which also needs to be zeroized in file `crate/kmip/src/kmip/kmip_operations.rs`.
