### ISSUE TITLE
Utils crate dependency on kmip

### ISSUE THREAD

**Issue by JosePisco** [Cosmian/kms#174]
`utils` crate should semantically not depend on `kmip` crate. This creates architectural inconsistencies in the KMS.

For example when writing a wrapper to zeroize the `BigUint` type, it cannot be written in `utils` and used in `kmip` whereas that's how you would do it.

**Comment by ThibsG** [comment]
You are right, https://github.com/Cosmian/kms/pull/165 started a rework of utils, moving all the crypto part into a `crypto` subcrate, but it appears that almost everything in it is tied to `kmip`, so maybe we should consider to move that `utils` (or `crypto`) inside `kmip` subcrate.

**Comment by ThibsG** [comment]
@JosePisco  I gave it a shot in this commit: https://github.com/Cosmian/kms/pull/165/commits/9a4ec30fce19e1f40781a1dbcb816b0d4bbf6c48

You can browse the files here: https://github.com/Cosmian/kms/tree/9a4ec30fce19e1f40781a1dbcb816b0d4bbf6c48

**Comment by JosePisco** [comment]
Sounds great to me, nice work!
