### ISSUE TITLE
Erroneous ID/Tag parsing

### ISSUE THREAD

**Issue by tbrezot** [Cosmian/kms#198]
This holds for all actions:
- The current implemented introduces an undocumented behavior when both `--id` and `--tag` are passed. Using an enum could solve the problem:
```rust
struct AddAttributeAction {
    access_policy: String,
    handle: KeyHandle,
}

enum KeyHandle {
    Id(String),
    Tags(Vec<String>),
}
```
- The parsing of tags may be checked against the empty vector. It is not clear for me how the current implementation behaves when passed `--tag` with an empty string. My guess would be an "UnknownKeyId" error returned from a call to the KMS. This corner case could be checked locally instead.

_Originally posted by @tbrezot in https://github.com/Cosmian/kms/pull/179#discussion_r1511330237_

**Comment by bgrieder** [comment]
Actually, this cannot happen, Clap prevents it:

```Rust
    /// The private master key unique identifier stored in the KMS
    /// If not specified, tags should be specified
    #[clap(long = "key-id", short = 'k', group = "key-tags")]
    secret_key_id: Option<String>,

    /// Tag to use to retrieve the key when no key id is specified.
    /// To specify multiple tags, use the option multiple times.
    #[clap(long = "tag", short = 't', value_name = "TAG", group = "key-tags")]
    tags: Option<Vec<String>>,
 ```
 The `group=key-tags` is what forces the alternative.
 
 Example when using `get-attributes`:
 
 ```sh
 ➜ ckms get-attributes -i efdd94f3-dc43-4742-961f-901f56bf8302 -t myrsakey
error: the argument '--id <ID>' cannot be used with '--tag <TAG>'
```

**Comment by bgrieder** [comment]
(the same is true for direct API calls)
