### ISSUE TITLE
Use something else than OpenSSL to be able to use `wrap`/`unwrap` in Windows

### ISSUE THREAD

**Issue by ThibsG** [Cosmian/kms#214]
https://github.com/Cosmian/kms/pull/209 disables the use of `wrap`/`unwrap` in CLI because it uses OpenSSL and we wanted the CLI to be usable in MacOS/Windows without OpenSSL.

Ref commit: https://github.com/Cosmian/kms/pull/209/commits/679fe9ff4f035cf40d9ce02f928f4dcecc262e88

**Comment by bgrieder** [comment]
Yes. We noticed that the other day.
In the CLI code, this feature is gated under the `openssl` cfg

https://github.com/Cosmian/kms/blob/bcf0acfdc41d1ba9a1b6470500e494b18b8900f8/crate/cli/src/actions/shared/mod.rs#L7

The default build should not enable this feature @Manuthor ?

Better fix: implement the functionality using pure Rust (but this will have to be excluded from FIPS builds)

**Comment by Manuthor** [comment]
Indeed, the default build does not enable the feature `openssl` on the `ckms`.
Agreed on the pure Rust implementation.
