### ISSUE TITLE
Better use of request attributes in import operations for new KMIP objects

### ISSUE THREAD

**Issue by JosePisco** [Cosmian/kms#226]
`import()` method at `crate/server/src/core/operations/import.rs` processes different objects (symmetric keys, public keys, private keys and certificates) after receiving an import request.

Attributes for the KMIP object created from this request are weirdly managed. This should be quite symmetrical from one type of key to the other.

**Comment by Manuthor** [comment]
done in https://github.com/Cosmian/kms/pull/239
