### ISSUE TITLE
Add object type granularity on revoke commands

### ISSUE THREAD

**Issue by ccorsin** [Cosmian/kms#258]
Curently, revoke commands (from sym keys, certify...) revoke all elements of a tag, not only the type of object associated with the beginning of the command.
**For each revokation action, only the associated object type should be revoked.**

**Comment by bgrieder** [comment]
Disagree.

If you want to reduce the revocation scope, use the objects IDs, rather than the tags.

When using the ides, multiple objects may still be revoked: there is no point keeping an RSA public key active, when its private key is revoked.

**Comment by bgrieder** [comment]
Won't fix for now. Will re-open it if we find a tangible use-case for reducing scope.
