### ISSUE TITLE
Better SQLCipher support

### ISSUE THREAD

**Issue by ThibsG** [Cosmian/kms#35]
* [ ] Allow the user to change his database secret
* [ ] Improve error messages (for a better user experience) concerning sqlcipher: bad password, bad group id, etc.
* [X] Remove all references to EdgelessDB: CI, docs, etc.
* [ ] Add the cli command `configure` in the public documentation 
* [X] When sqlcipher will include sqlite>=3.8, remove the feature sqlcipher from Cargo.toml and enable `libsqlite3-sys/bundled-sqlcipher-vendored-openssl` by default. Follow: https://github.com/sqlcipher/sqlcipher/issues/427

**Comment by bgrieder** [comment]
Use of SQLCipher has been replaced by redis-findex, which offers a much better paradigm.
SQLCipher is still supported as a backend but is unlikely to receive much enhancement.
