### ISSUE TITLE
Reuse reexports when available

### ISSUE THREAD

**Issue by ThibsG** [Cosmian/kms#51]
From this comment in `crate/utils/Cargo.toml` (https://github.com/Cosmian/kms/pull/50/files#diff-40079c98666ae41537dc13a6af64fa3309522e94bbd79b8e352d4c679e12320cR14):
> cosmian_crypto_core = "9.3.0"       # Must use `crypto_core` from `cloudproof_rust` reexport

**Comment by bgrieder** [comment]
I have made the fix for kms_utils in the branch fixing #71

**Comment by Manuthor** [comment]
also done in released version 4.9.0
