### ISSUE TITLE
Certificates should be saved in DER format for KMIP compliance

### ISSUE THREAD

**Issue by bgrieder** [Cosmian/kms#72]
As indicated by KMIP 2.1 for Certificates: `It is a DER-encoded X.509 public key certificate.` 
Certificates are currently saved in PEM format.

https://github.com/Cosmian/kms/blob/ba947bc8ffe875c4fe494718b432d13708df2938/crate/cli/src/actions/certificates/import_certificate.rs#L86

This change will require a database upgrade. see #73

**Comment by Manuthor** [comment]
done in released version 4.8.2
