### ISSUE TITLE
Migrate from 'num-bigint' to ´num-bigint-dig'

### ISSUE THREAD

**Issue by bgrieder** [Cosmian/kms#74]
´num-bigint' is not constant time. BigUints are used to store key material data (e.g. RSA).
This is only used for storage, not computation so there should not be any security issue.
However, to prevent potential misuse, use of the constant time version would be preferred.

Note: this change is likely to create havoc in the ser/de of TTLV

**Comment by Manuthor** [comment]
done in released version 4.9.0
