### ISSUE TITLE
Improve KMIP `Attributes` support

### ISSUE THREAD

**Issue by bgrieder** [Cosmian/kms#88]
Kmip managed objects (`Objects`) are associated with attributes ( `Attributes`).
These attributes contain meta information on the object, in particular links to other objects.

To store the attributes, the current implementation relies on a nested `Attributes` property inside the [`KeyValue`](https://docs.oasis-open.org/kmip/kmip-spec/v2.1/os/kmip-spec-v2.1-os.html#_Toc57115548), located inside a `KeyBlock` which is itself inside the `Object`.

This implementation is problematic for a few reasons:

- Some `Object`s such as `Certificate` do not have a nested `Attributes` property where to store them, and attributes are lost on Import or not generated on Create.  The current implementation partially compensates with the use of tags, but this is limited and non-standard. 
- The current implementation prevents the use of the `Locate` operation to find `Object` that is not holding attributes.
- With regards to the `Attributes` nested inside the `KeyValue`, KMIP specifies they should merely be a copy of the "main" attributes

> This attribute information differs from the attributes associated with Managed Objects, and is obtained via the Get Attributes operation, only by the fact that it is encapsulated with (and possibly wrapped with) the key material itself.

### Proposed change

This ticket proposes to change the storage layer so that it stores the tuple `(Object, Attributes)` rather than just the `Object`. This would affect the `Database` trait in `crate/server/src/database/database_trait.rs` and its specific DB implementations.

The `Locate` operation should be updated to search these top-level Attributes.
The `Import` operation should be updated accordingly.

**Comment by bgrieder** [comment]
@Manuthor Was this fixed by #166 and should it be closed ?

**Comment by Manuthor** [comment]
Fixed in #166
